// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTQ44wr5UkBKlxSK5Hn86DtamdniDWLaM',
    appId: '1:356749768011:web:da815f61b51cdaed12a4ce',
    messagingSenderId: '356749768011',
    projectId: 'salondebelleza-2f326',
    authDomain: 'salondebelleza-2f326.firebaseapp.com',
    storageBucket: 'salondebelleza-2f326.firebasestorage.app',
    measurementId: 'G-J8TR37S9DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Y3lZU6t3Y9EPKovO2ml3g4XXU16Y9ow',
    appId: '1:356749768011:android:9692236daaa789a012a4ce',
    messagingSenderId: '356749768011',
    projectId: 'salondebelleza-2f326',
    storageBucket: 'salondebelleza-2f326.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfy1pGETkDedD-VDr0FjzV0X6_uGsK1Tc',
    appId: '1:356749768011:ios:6fdb55de4af7272b12a4ce',
    messagingSenderId: '356749768011',
    projectId: 'salondebelleza-2f326',
    storageBucket: 'salondebelleza-2f326.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfy1pGETkDedD-VDr0FjzV0X6_uGsK1Tc',
    appId: '1:356749768011:ios:6fdb55de4af7272b12a4ce',
    messagingSenderId: '356749768011',
    projectId: 'salondebelleza-2f326',
    storageBucket: 'salondebelleza-2f326.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTQ44wr5UkBKlxSK5Hn86DtamdniDWLaM',
    appId: '1:356749768011:web:7253a5e427110c7312a4ce',
    messagingSenderId: '356749768011',
    projectId: 'salondebelleza-2f326',
    authDomain: 'salondebelleza-2f326.firebaseapp.com',
    storageBucket: 'salondebelleza-2f326.firebasestorage.app',
    measurementId: 'G-34YEGD8NNJ',
  );
}
