# --- Pega este contenido exacto en tu Podfile ---

platform :ios, '13.0'
use_frameworks!

# Pods for Runner
target 'Runner' do
  pod 'GoogleUtilities', '8.0.0' # Resuelve conflictos de versiones

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end