name: Build iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Clean and get dependencies
      run: |
        cd ios
        rm -rf Pods
        rm -rf Podfile.lock
        cd ..
        flutter clean
        flutter pub get
      
    - name: Build iOS
      run: flutter build ios --release --no-codesign
      
    - name: Archive IPA
      run: |
        cd build/ios/iphoneos
        mkdir Payload
        mv Runner.app Payload/
        zip -r app.ipa Payload/
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: build/ios/iphoneos/app.ipa